language: python

matrix:
  include:
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.7-dev
      dist: xenial
      sudo: true
    - python: 3.8-dev
      dist: xenial
      sudo: true

install:
  - pip install --upgrade setuptools wheel black
  - python setup.py install

script:
  - black --check bwapi test
  - python setup.py test

