language: python

matrix:
  include:
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.7-dev
      dist: xenial
      sudo: true
    - python: 3.8-dev
      dist: xenial
      sudo: true

env:
  global:
  - secure: M8bYMhmrXlvUIkEINiYPmv1f8WiuI1nG5+73wVizxzF2aP3oDzlk58c6IK+drYewuaWq4n1moEA3gbpAge7fTycofx2BHoseyR4DVlzfS18BrgzE4gyU7lVmMniF27Jf8+u3Zo7b6jCt+Ew6qHurkWIEUR8/jOvQkk3WgMBUFeY1EBVFKT37nS00gZKmifbpydP1uP2qaWkoyr1UyfNcRUHgaLyCKPGx5DLfkVBg/6zP+ORC/wbu17aDrf474oLfdOwNg0GJMeXHzWjlxFR54DUqQ9gj95hx1N6VdKB7D1uLsEDl7UGcvD2sDW3bFQhjsh3tKYEkXYJ14fFDGfEijsIu7yCH+2r+hxgUvHbrXyRxbv9THO3uRDBGGDc6GzY2nxUF3ypCHSU9V7eS8NFOC5DDw7eICErQMxbWusFBuQJAWutOKRDArKRTsTYu26iHlKDwviYpoQKRLoeeWAUZJVZJIZJSFtb8Ozwu6bQ4CvNrPdhnJnGtagFfoqDmiNm8i/m1g+U5neB0Pj3e4aUbZHMBSfnci9leGjH9Oer3qhcct1BI5osRA72D6OJGNTyWkzFMahVZynE79grgd0lDaJn5zin3YjkIvUS9aFNk9gDOC4MQY8/7GDHUpcRvQZ69FXNclrtU9p9hB8OK+vcFgHXXnFLe6D5CCQzGnzPLeYg=
  - secure: KwtIECNhm0JDXyD2Q12cAZPY1FL7zilXHFz8BV0Oe1Jk98iK/bHTVc4VpJxhz/1ewdelfROgm7IOE3vTfV8J3UG38AXrWFiZVWuZHX1TAZZKP+e1+YcD8YjnqLbYKP3dJJ4nOwTsRCG+MNvZT1Xh1jMwhrI6JzvT6avE2DY76WbdBhShaDD/KzIaZXLZqxM6VOYuAUYKO3eiIa0BdqoBPNHXmFtrPq1ZBzNheWb1a6idAiqM3NDJJYXVpRP6/UBAAlzwrXw/HblXHdrqJMY9pqO+4SY8tsqCWYIeCLXp12eyBLX2gy+dBJ0/2sP7krywGsA6KEqiyVbKJc/Ad4mir+qaWzRpUYL36VALxUXoQ5pta3oIMSs1IHd0a+NiBu9uLL65sefUma17pyplJXOUM++kp8bc42v2aKpivQDxCdedd4KQ2RRdXBUcCir/2Kw2dtGk1qHPcdnjohrZQ1ug+u1gVbNagoy8FJmVMOFBUr7gcwGwCEx+Asa7O8tqXfL7rRH6ms9a/USOiL4k4DRZF1bukBkyrEaznlzWe61yZvF25kCq55GQeQEBWunpm+rZ04BYZNFCuN1XnhO88EZAHoX1E4EHzU1hLv8sUYYrqMnQBECKB+ksjwAQhQgjYHyXpNIZhNAqOqf24s9GX/75zD2W8tIQXprpt6K8Omvn730=
  - secure: JzXIjvNSfMf9YO4oP0RZRAJgevp51W12W08iGAggnWjNZNFLPtqMS8UdYwpWA/h66zLVuvoq3jFI19bUz7wvfM39TFLhjeWUhJqBkHGXUlOqBvncvIgo4xrQuAxirRxVKOU2KwDl5eU6JAWYnbcGP56pU+9zeRTvdkrWboP7DNMqFkDP8mfP6zgbx0GFOUddXoHS6VHdS1j2LjZ7+BlbtDt2ehAtgHhutz4/WVq4GRjx8qQPHFKkOj823C7pZCtgLTqTZH3qPMBgcU73N/9vV7ATA1Geg3RQhdULsLLNRKNlBYbNfDuH46UH9dOjz88bZwpOLLL3uUAkp+3ZP6PUTZ97Q+xGCz/pZant4EhNANA4kINKmxGy7QH1PDDB45ANrDddSG5uV7pZR72inTv9y+zvozOwGgyNMq50FLc3RZM1sfj9MBNCV8caSEOlYmeCA+JRoNuCehro7HRL88av1IYQ9Dmv3NZRhO/l67FNLOXwPwDL2GuCs1VLHBNO8xEWeKwms+0ZE9cInlmhid6CZa8fsP5lszQdxH9/JyKsvxtWlCsVL4Qq2pZe9ihBvLfO4O8yKSuv9KoKd+S8so6WxdxtSF8xS/FEycgzATkQgnn+MW8ZHlsSmFLHTnVdByv5Xan3TGYrIXl1AWdt8iS3P2muswq8crLKAIxwKEVAMSM=

install:
  - python setup.py install

before_script:
  - python authenticate.py --username "$BWAPI_USERNAME" --password "$BWAPI_PASSWORD"

script:
  - export BWAPI_USERNAME
  - export BWAPI_PROJECT
  - python setup.py test
