language: python

matrix:
  include:
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.7-dev
      dist: xenial
      sudo: true
    - python: 3.8-dev
      dist: xenial
      sudo: true

env:
  global:
  - BWAPI_USERNAME=hamish@brandwatch.com
  - BWAPI_PROJECT=API SDK Test
  - secure: "J5tD6vyXRj23iM76OE5aprDLiolLDQa6qXHiZ70UEd6Zm2i9w66l0/EpajL53fIpIquptP9s2BCQl/rL8GbEWn5HjqbLteJHoYr2L2RYJozO/sdZnFShWzpIdfMiznYwSDKq4lBrFBY/JqGdlbpxYuTL14cwjXshzTZRr0G071QejztliNNZ+C/MRsr2u1KUFSwow5ZV0D1fycUaXU1FPAIds+vDuDvWtUTHPiPFfzdNzg7HHRVpIttb47TStZXBdmYckXrFcZsjCKS+8+F48lI1O0WdpM6yvThI6Hnbpx4mPn3E3mTvwonGHGy0kQikn20RhqBFCPKB3a3zSzq+NGnikRWiPm+F8YnIZSZJ2KibhL6dIlByyUCSvsFomLvB1gF6EOAjOx2eSVzlY2LoS2VKpA1kmhf6S+6ynEmLn6NONok5hlTza1XU5iKU9aZyokr0K7mvxjMTguTRKe5v4lCi2WycozZ7JfTsC1uV4szCc+06uQsCnw/H2wGmhLfk6VH2pKlVQAi/sCh4zgJ0zyb8fVug+YYhWBdov6Q/MWZl6GJ6/mivgshZgpkSZcq4OeoK1+c+7Fvv3Z3HAFDmAvbdt9n5TJj1dnwrfhguMxPrHXHtNpvtns+P5+lzKHZwKm1poGcC8msQjfViGz9I2jiiHS8GAwuFT7QtJlke62I="

install:
  - python setup.py install

before_script:
  - python authenticate.py --username "$BWAPI_USERNAME" --password "$BWAPI_PASSWORD"

script:
  - python setup.py test
